<a href="https://colab.research.google.com/github/ChitraChaudhari/GC_DataEngineering_Bootcamp/blob/main/EDA/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
L= [1,2,3]  #Python list

In [3]:
A= np.array([1,2,3]) #array

In [4]:
for e in L:
  print(e)

1
2
3


In [5]:
for e in A:
  print(e)

1
2
3


In [6]:
L.append(4)
L

[1, 2, 3, 4]

In [7]:
A.append(4)

AttributeError: ignored

In [10]:
L + [5]

[1, 2, 3, 4, 5]

In [11]:
A + np.array([4]) #broadcasting

array([5, 6, 7])

In [13]:
A

array([1, 2, 3])

In [12]:
A + np.array([4,5,6])

array([5, 7, 9])

In [14]:
A + np.array([4,5])

ValueError: ignored

In [15]:
A

array([1, 2, 3])

In [16]:
2 *A    #Broadcasting

array([2, 4, 6])

In [18]:
L

[1, 2, 3, 4]

In [17]:
2*L

[1, 2, 3, 4, 1, 2, 3, 4]

In [20]:
L2 = [e*2 for e in L]
L2

[2, 4, 6, 8]

In [21]:
A**2

array([1, 4, 9])

In [22]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [23]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [24]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [26]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

#**List looks like an array, but works more like a generic data structure. But numpy array exists specifically to do maths**

In [27]:
a = np.array([15, 35, 55])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[15 35 55]


**ndarray.ndim:** The number of axes (dimensions) of the array.

**ndarray.shape:** This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.

**ndarray.size**: The total number of elements of the array. This is equal to the product of the elements of shape.

**ndarray.dtype:** Provides the data type of the elements in the array. You can specify the standard Python data types or use additional data types provided by NumPy, e.g., numpy.int32, numpy.int16, and numpy.float64 etc.

In [28]:
print(a.dtype)  # Prints the datatype of items stored 
print(a.ndim)   # Prints the array dimension
print(a.shape)  # Prints the array shape
print(a.size)   # Prints the array size


int64
1
(3,)
3


In [30]:
b = np.array([[2],[-8],[-7]])
print(b)

[[ 2]
 [-8]
 [-7]]


In [31]:
print(b.dtype)  # Prints the datatype of items stored 
print(b.ndim)   # Prints the array dimension
print(b.shape)  # Prints the array shape
print(b.size)   # Prints the array size

int64
2
(3, 1)
3


In [35]:
a = np.array([15, 35, 55], dtype=complex)
print(a)


[15.+0.j 35.+0.j 55.+0.j]


In [33]:
print(np.array([1.0, 1.5, 2.0, 2.5]).dtype)             # Float type
print(np.array([True, False, True]).dtype)              # Boolean type
print(np.array(['AL', 'AK', 'AZ', 'AR', 'CA']).dtype)   # Unicode 2 characters


float64
bool
<U2


In [36]:
states = np.array(['AL', 'AK', 'AZ', 'AR', 'CA'])

print(states[0])

AL


In [37]:
print(states[1:3])

['AK' 'AZ']


In [40]:
print(states[-1:])

['CA']


In [41]:
print(states[:])

['AL' 'AK' 'AZ' 'AR' 'CA']


In [42]:
scores = np.array([92, 34, 88, 80, 73, 100, 100])

print(scores.mean())   # Prints the mean of the array elements
print(scores.max())    # Prints the max value in the array
print(scores.min())    # Prints the min value in the array
print(scores.argmin()) # Prints the index number of the min value
print(scores.std())    # Prints the standard deviation of the array elements


81.0
100
34
1
21.26700999872136


In [43]:
np.median(scores)

from scipy import stats
stats.mode(scores)


ModeResult(mode=array([100]), count=array([2]))

In [44]:
mixed_array = np.array(['1', 2, np.nan])
print (mixed_array)
print (type(mixed_array[1]))


['1' '2' 'nan']
<class 'numpy.str_'>
