<a href="https://colab.research.google.com/github/ChitraChaudhari/GC_DataEngineering_Bootcamp/blob/main/EDA/NumPy_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy

##Problem 1

A developer is trying to add two lists using Matrix addition. However the expressions that are written below is not solving this problem correctly. Fix it using NumPy structures

In [2]:
import numpy as np

a = np.array([4, 5, 6])
b = np.array([3, 4, 5])
c = a + b
c

array([ 7,  9, 11])

In [3]:
#Testcase
np.testing.assert_array_equal(c, [7, 9, 11])
print("Test Passed!")

Test Passed!


##Problem 2

The below array provides the marks that a student has earned in 4 tests for a total of 17 marks in each test. Create another array that shows the percentage of the marks obtained by this student in each test.

In [4]:

marks = np.array([12, 14.5, 16, 16.5])
marks_in_percent =marks*(100/17)
type(marks_in_percent)

numpy.ndarray

In [6]:
12*(100/17)

70.58823529411765

In [7]:
#TestCase
np.testing.assert_allclose(marks_in_percent, [70.58823529, 85.29411765, 94.11764706, 97.05882353])
print("Test passed!")

Test passed!


## Problem 3

Find both the type and dtype of the given NumPy Array


In [5]:
import numpy as np
a = np.array([3.0, 4, 8])
a_type =type(a)
a_dtype = a.dtype


In [8]:
#TestCase
assert(a_type == np.ndarray)
assert(a_dtype == np.float64)
print("Test passed!")

Test passed!


In [9]:
a=np.array([2,-8,-7])
b = np.array([[2],[-8],[-7]])
print(a*b)

[[  4 -16 -14]
 [-16  64  56]
 [-14  56  49]]
